### PR TITLE
Added Deposit Classes and Examples

### PR DESCRIPTION
**Pull request by ArtVaz**
Hi, 
I've added Classes for creating deposit in quickbook. 
Please, confirm it if changes meet to your standards.

### CODE REVIEW

**Comment by domaniak** [comment]
Hi, I get a "5010: [Stale Object Error, Stale Object Error" when I create a new Deposit. I don't understand how this is possible because it's an insert.. Is there anyone who know why?

I have multiple SaleReceipt line attache to the deposit, and I make sure they are in the 'Undeposed account" before I create the Deposit.

For this deposit, I have also 2 refunds concerning related to the same SaleReceipt...

**Comment by consolibyte** [comment]
@domaniak   How is that even remotely related to the pull request that you're commenting on? If this is a separate issue, please create a separate issue instead of commenting on an unrelated one.

**Comment by domaniak** [comment]
I'm sorry if it seem not related, but I had question about creating a Deposit, and this pull request added the fonctionnality of creating the Deposit, so I tough that maybe the programmer who create this feature will know more about Deposit, or had experience

**Comment by consolibyte** [comment]
Please open a separate issue, they are unrelated - https://github.com/consolibyte/quickbooks-php/issues

**Pull request merged**
