### PR TITLE
Fix redefinition of parameters fatal error for PHP7 compatibility

### PR DESCRIPTION
**Pull request by kitsunenokenja**
Redefinition of parameters is now a fatal error in PHP7.0+. This patch corrects the calls to the callback class from the handlers class, and includes a few PHPDoc corrections which were falsely labeled, misleading IDE's parsing them.

*Note: my IDE automatically strips trailing whitespace which these files had very many of, sorry about the resulting long diff*

### CODE REVIEW

**Comment by mfrederico** [comment]
I'm running into this issue with php7 - This is a valid pull request.

**Comment by garrensweet** [comment]
+1. I just ran into this issue today, and this is a valid pull. The patch provided by @kitsunenokenja correctly resolves the issue. Can we get this merged?

**Comment by leebria** [comment]
+1. Running with Homestead and Laravel 5.2 and encountering this.

**Comment by kitsunenokenja** [comment]
The insane amount of time it's taking for this patch to be accepted has essentially singlehandedly quelled any interest I may have had in contributing subsequent corrections for this project. It's ridiculous that something so trivial and severe for PHP7 sits here for months. It's embarrassing that PHP5 even allowed this mistake and that it's taken until version 7 for the PHP engine to mark this as unacceptable, but I suppose that's neither here nor there. Critical issues affecting the production usage I'm responsible for creating a need for another patch notwithstanding, this serves as my last pull request.

**Comment by consolibyte** [comment]
Sorry for the slow response on the merge. If you could please try to submit merge requests that don't result in the long diffs, it would be much easier to merge in.

**Pull request merged**
